[package]
name = "qabot-tg"
version = "0.1.0"
authors = ["Gestalt LUR <gestapolur@users.noreply.github.com>"]

[dependencies]
rocket = "0.3.2"
rocket_codegen = "0.3.2"
rocket_contrib = "0.3.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.7"
error-chain = "0.11"